import olympus from "./../../../assets/images/olympus.jpg";
import marijuana from "../../../assets/images/marijuana.jpg";
import banner from "../../../assets/images/banner.jpg";
import featured from "../../../assets/images/featured.png";
import product from "../../../assets/images/product.png";

const makeProducts = (shopId, shopName, ownerName) => [
    {
        _id: `${shopName}-p1`, shop: {_id: shopId, name: shopName}, owner: {fullName: ownerName},
        rating: {average: 4.8, count: 124},
        price: {amount: 45, currency: 'GHS'}, description: 'Premium indica strain with deep relaxation effects and earthy pine aroma.',
        strain: 'Indica', status: 'active', image: marijuana, name: 'Purple Kush OG', category: 'Flower',
        thc: '24', cbd: '0.5', featured: true,
    },
    {
        _id: `${shopName}-p2`, shop: {_id: shopId, name: shopName}, owner: {fullName: ownerName},
        rating: {average: 4.6, count: 89},
        price: {amount: 55, currency: 'GHS'}, description: 'Energizing sativa with citrus notes. Perfect for daytime use and creativity.',
        strain: 'Sativa', status: 'active', image: product, name: 'Lemon Haze', category: 'Flower',
        thc: '21', cbd: '1.2', featured: false,
    },
    {
        _id: `${shopName}-p3`, shop: {_id: shopId, name: shopName}, owner: {fullName: ownerName},
        rating: {average: 4.9, count: 201},
        price: {amount: 60, currency: 'GHS'}, description: 'Balanced hybrid offering both mental uplift and body relaxation.',
        strain: 'Hybrid', status: 'active', image: marijuana, name: 'Blue Dream', category: 'Flower',
        thc: '22', cbd: '2.0', sale: true,
    },
];

export const shops = [
    {
        _id: 'shop-001',
        owner: {fullName: 'Dr. Maya Chen', _id: 'owner-001', phone: '+1 (702) 420-0001'},
        contact: {phone: '+1 (702) 420-0001', email: 'greenleaf@ruderalis.com'},
        name: 'Green Leaf Wellness',
        description: 'Our flagship dispensary in the heart of Las Vegas. Full-service patient consultations, lab-tested flower, edibles, and concentrates. Open 7 days a week with same-day delivery.',
        status: 'open',
        location: '420 Green Street, Las Vegas, NV 89101',
        rating: {average: 4.9, count: 342, details: {five: 65, four: 20, three: 10, two: 3, one: 2}},
        image: olympus,
        featured: true,
        shipping: {
            fee: 5.00,
            freeAbove: 50,
            estimatedDays: '1-3',
            areas: ['Las Vegas', 'Henderson', 'North Las Vegas'],
            policy: 'Free delivery on orders over $50. Same-day delivery available for orders placed before 2PM.',
        },
        products: makeProducts('shop-001', 'Green Leaf Wellness', 'Dr. Maya Chen'),
        reviews: [
            {_id: 'r1', user: {fullName: 'Maria Santos'}, rating: 5, text: 'Best dispensary in Vegas. The staff is incredibly knowledgeable and the flower is always fresh.', createdAt: '2025-12-01T10:00:00Z'},
            {_id: 'r2', user: {fullName: 'David Chen'}, rating: 4.5, text: 'Great selection and fast delivery. The edibles are perfectly dosed every time.', createdAt: '2025-11-15T14:00:00Z'},
        ],
    },
    {
        _id: 'shop-002',
        owner: {fullName: 'James Okafor', _id: 'owner-002', phone: '+1 (702) 420-0002'},
        contact: {phone: '+1 (702) 420-0002', email: 'highdesert@ruderalis.com'},
        name: 'High Desert Dispensary',
        description: 'Craft cannabis cultivated in small batches. We specialize in rare genetics and limited-edition strains. Connoisseur-grade flower for the discerning patient.',
        status: 'open',
        location: '888 Desert Bloom Ave, Henderson, NV 89012',
        rating: {average: 4.7, count: 218, details: {five: 55, four: 25, three: 12, two: 5, one: 3}},
        image: marijuana,
        featured: true,
        shipping: {
            fee: 7.00,
            freeAbove: 60,
            estimatedDays: '2-4',
            areas: ['Henderson', 'Las Vegas', 'Boulder City'],
            policy: 'Free delivery on orders over $60. Weekend delivery available with a $3 surcharge.',
        },
        products: makeProducts('shop-002', 'High Desert Dispensary', 'James Okafor'),
    },
    {
        _id: 'shop-003',
        owner: {fullName: 'Sarah Mitchell', _id: 'owner-003', phone: '+1 (702) 420-0003'},
        contact: {phone: '+1 (702) 420-0003', email: 'canopy@ruderalis.com'},
        name: 'The Canopy Club',
        description: 'Members-only dispensary with exclusive access to premium strains, VIP events, and personalized wellness programs. Elevate your cannabis experience.',
        status: 'open',
        location: '1200 Strip View Dr, Las Vegas, NV 89109',
        rating: {average: 4.8, count: 156, details: {five: 60, four: 22, three: 10, two: 5, one: 3}},
        image: banner,
        featured: true,
        shipping: {
            fee: 0,
            freeAbove: 0,
            estimatedDays: '1-2',
            areas: ['Las Vegas', 'Paradise', 'Spring Valley'],
            policy: 'Complimentary delivery for all members. Priority same-day delivery on all orders.',
        },
        products: makeProducts('shop-003', 'The Canopy Club', 'Sarah Mitchell'),
    },
    {
        _id: 'shop-004',
        owner: {fullName: 'Marcus Rivera', _id: 'owner-004', phone: '+1 (702) 420-0004'},
        contact: {phone: '+1 (702) 420-0004', email: 'emerald@ruderalis.com'},
        name: 'Emerald Therapeutics',
        description: 'Medical-focused dispensary with licensed pharmacists on staff. Specializing in CBD products, tinctures, and therapeutic cannabis solutions for chronic conditions.',
        status: 'closed',
        location: '500 Wellness Way, North Las Vegas, NV 89030',
        rating: {average: 4.6, count: 287, details: {five: 50, four: 28, three: 14, two: 5, one: 3}},
        image: featured,
        shipping: {
            fee: 4.00,
            freeAbove: 40,
            estimatedDays: '1-3',
            areas: ['North Las Vegas', 'Las Vegas', 'Nellis AFB'],
            policy: 'Free delivery on orders over $40. Expedited delivery available for medical patients.',
        },
        products: makeProducts('shop-004', 'Emerald Therapeutics', 'Marcus Rivera'),
    },
    {
        _id: 'shop-005',
        owner: {fullName: 'Aisha Johnson', _id: 'owner-005', phone: '+1 (702) 420-0005'},
        contact: {phone: '+1 (702) 420-0005', email: 'roots@ruderalis.com'},
        name: 'Roots & Remedies',
        description: 'Community-focused dispensary committed to social equity and patient education. Affordable access to quality cannabis with sliding-scale pricing for qualifying patients.',
        status: 'open',
        location: '750 Community Blvd, Las Vegas, NV 89106',
        rating: {average: 4.5, count: 198, details: {five: 45, four: 30, three: 15, two: 7, one: 3}},
        image: olympus,
        featured: true,
        shipping: {
            fee: 3.00,
            freeAbove: 35,
            estimatedDays: '2-4',
            areas: ['Las Vegas', 'North Las Vegas', 'Sunrise Manor'],
            policy: 'Free delivery on orders over $35. Sliding-scale delivery fees for qualifying patients.',
        },
        products: makeProducts('shop-005', 'Roots & Remedies', 'Aisha Johnson'),
    },
    {
        _id: 'shop-006',
        owner: {fullName: 'Dr. Elena Vasquez', _id: 'owner-006', phone: '+1 (702) 420-0006'},
        contact: {phone: '+1 (702) 420-0006', email: 'altitude@ruderalis.com'},
        name: 'Altitude Cannabis Co.',
        description: 'Premium dispensary with rooftop lounge and consumption area. Curated selection of artisan flower, craft edibles, and luxury accessories. The elevated cannabis experience.',
        status: 'open',
        location: '2100 Skyline Terrace, Las Vegas, NV 89102',
        rating: {average: 4.9, count: 412, details: {five: 70, four: 18, three: 8, two: 3, one: 1}},
        image: marijuana,
        featured: true,
        shipping: {
            fee: 6.00,
            freeAbove: 55,
            estimatedDays: '1-2',
            areas: ['Las Vegas', 'Spring Valley', 'Summerlin'],
            policy: 'Free delivery on orders over $55. VIP members receive complimentary same-day delivery.',
        },
        products: makeProducts('shop-006', 'Altitude Cannabis Co.', 'Dr. Elena Vasquez'),
    },
];
