import image from "./../../../assets/images/marijuana.jpg";
import product from "./../../../assets/images/product.png";
import featured from "./../../../assets/images/featured.png";

const reviews = [
    {_id: 'rev-1', user: {fullName: 'Maria Santos'}, rating: 5, text: 'Incredible strain. Smooth smoke with a relaxing body high that lasts for hours. Perfect for my chronic pain.', createdAt: '2025-11-20T10:00:00Z'},
    {_id: 'rev-2', user: {fullName: 'David Chen'}, rating: 4, text: 'Great flavor profile with earthy and pine notes. Effects are strong but not overwhelming. Good for evening use.', createdAt: '2025-11-15T14:00:00Z'},
    {_id: 'rev-3', user: {fullName: 'Aisha Johnson'}, rating: 5, text: 'This is hands down the best flower I have tried from Ruderalis. The terpene profile is outstanding.', createdAt: '2025-10-28T09:00:00Z'},
    {_id: 'rev-4', user: {fullName: 'James Okafor'}, rating: 4.5, text: 'Consistently good quality. The packaging is discreet and the product arrives fresh every time. Highly recommend for anxiety relief.', createdAt: '2025-10-10T16:00:00Z'},
    {_id: 'rev-5', user: {fullName: 'Sarah Mitchell'}, rating: 5, text: 'The lab report on this strain is impressive. Clean, potent, and exactly what was advertised. Ruderalis sets the standard.', createdAt: '2025-09-22T11:00:00Z'},
];

export const products = [
    {
        _id: 'prod-001',
        shop: {_id: 'shop-001', name: 'Green Leaf Wellness', contact: {phone: '+1 (702) 420-0001', email: 'greenleaf@ruderalis.com'}},
        owner: {fullName: 'Dr. Maya Chen'},
        rating: {average: 4.8, count: 124, details: {five: 60, four: 25, three: 10, two: 3, one: 2}},
        price: {amount: 45, currency: 'GHS'},
        description: 'Purple Kush OG is a pure indica strain known for its deep relaxation and sedative effects. With rich terpene profiles of myrcene and linalool, it delivers an earthy, sweet grape aroma. Ideal for evening use, pain relief, and insomnia. Lab-tested at 24% THC.\n\nTerpene Profile: Myrcene (dominant), Linalool, Caryophyllene\nEffects: Relaxed, Sleepy, Happy, Euphoric\nFlavors: Grape, Earthy, Sweet\nMay help with: Pain, Insomnia, Stress, Anxiety',
        strain: 'Indica', status: 'active', category: 'Flower',
        image, name: 'Purple Kush OG',
        thc: '24', cbd: '0.5', featured: true, sale: false,
        reviews,
        createdAt: '2025-06-15T10:00:00Z',
    },
    {
        _id: 'prod-002',
        shop: {_id: 'shop-002', name: 'High Desert Dispensary', contact: {phone: '+1 (702) 420-0002', email: 'highdesert@ruderalis.com'}},
        owner: {fullName: 'James Okafor'},
        rating: {average: 4.6, count: 89, details: {five: 50, four: 28, three: 12, two: 7, one: 3}},
        price: {amount: 55, currency: 'GHS'},
        description: 'Lemon Haze is an energizing sativa-dominant strain with a bright citrus aroma and uplifting cerebral effects. High in limonene terpenes, it is perfect for daytime use, creativity, and social activities. Lab-tested at 21% THC with 1.2% CBD.\n\nTerpene Profile: Limonene (dominant), Terpinolene, Pinene\nEffects: Energetic, Happy, Uplifted, Creative\nFlavors: Lemon, Citrus, Sweet\nMay help with: Depression, Fatigue, Stress, Lack of appetite',
        strain: 'Sativa', status: 'active', category: 'Flower',
        image: product, name: 'Lemon Haze',
        thc: '21', cbd: '1.2', featured: true, sale: true,
        reviews: [reviews[0], reviews[2], reviews[4]],
        createdAt: '2025-07-20T10:00:00Z',
    },
    {
        _id: 'prod-003',
        shop: {_id: 'shop-003', name: 'The Canopy Club', contact: {phone: '+1 (702) 420-0003', email: 'canopy@ruderalis.com'}},
        owner: {fullName: 'Sarah Mitchell'},
        rating: {average: 4.9, count: 201, details: {five: 70, four: 18, three: 8, two: 3, one: 1}},
        price: {amount: 60, currency: 'GHS'},
        description: 'Blue Dream is a legendary hybrid that balances full-body relaxation with gentle cerebral invigoration. Sweet berry aroma from its Blueberry indica and Haze sativa genetics. The go-to strain for both novice and veteran patients.\n\nTerpene Profile: Myrcene (dominant), Pinene, Caryophyllene\nEffects: Relaxed, Happy, Euphoric, Creative\nFlavors: Berry, Sweet, Herbal\nMay help with: Stress, Pain, Depression, Headaches',
        strain: 'Hybrid', status: 'active', category: 'Flower',
        image: featured, name: 'Blue Dream',
        thc: '22', cbd: '2.0', featured: true, sale: false,
        reviews,
        createdAt: '2025-08-10T10:00:00Z',
    },
    {
        _id: 'prod-004',
        shop: {_id: 'shop-004', name: 'Emerald Therapeutics', contact: {phone: '+1 (702) 420-0004', email: 'emerald@ruderalis.com'}},
        owner: {fullName: 'Marcus Rivera'},
        rating: {average: 4.7, count: 156, details: {five: 55, four: 25, three: 12, two: 5, one: 3}},
        price: {amount: 40, currency: 'GHS'},
        description: 'Northern Lights is one of the most famous indica strains of all time. Known for its resinous buds, fast flowering, and resilient growth. Delivers a deeply relaxing experience with sweet and spicy aromas of pine and earth.\n\nTerpene Profile: Myrcene (dominant), Caryophyllene, Pinene\nEffects: Relaxed, Sleepy, Happy, Euphoric\nFlavors: Pine, Earthy, Sweet, Spicy\nMay help with: Insomnia, Pain, Stress, Depression',
        strain: 'Indica', status: 'active', category: 'Flower',
        image, name: 'Northern Lights',
        thc: '18', cbd: '0.8', featured: false, sale: true,
        reviews: [reviews[1], reviews[3]],
        createdAt: '2025-05-01T10:00:00Z',
    },
    {
        _id: 'prod-005',
        shop: {_id: 'shop-005', name: 'Roots & Remedies', contact: {phone: '+1 (702) 420-0005', email: 'roots@ruderalis.com'}},
        owner: {fullName: 'Aisha Johnson'},
        rating: {average: 4.5, count: 98, details: {five: 45, four: 30, three: 15, two: 7, one: 3}},
        price: {amount: 50, currency: 'GHS'},
        description: 'Girl Scout Cookies (GSC) is a potent hybrid with a sweet and earthy aroma. Known for full-body euphoria paired with a time-warping cerebral high. Rich in caryophyllene and limonene terpenes. A patient favorite for stress and depression.\n\nTerpene Profile: Caryophyllene (dominant), Limonene, Humulene\nEffects: Euphoric, Happy, Relaxed, Creative\nFlavors: Sweet, Earthy, Pungent\nMay help with: Stress, Depression, Pain, Nausea',
        strain: 'Hybrid', status: 'active', category: 'Flower',
        image: product, name: 'Girl Scout Cookies',
        thc: '25', cbd: '0.3', featured: true, sale: false,
        reviews: [reviews[0], reviews[1], reviews[2], reviews[4]],
        createdAt: '2025-09-05T10:00:00Z',
    },
    {
        _id: 'prod-006',
        shop: {_id: 'shop-006', name: 'Altitude Cannabis Co.', contact: {phone: '+1 (702) 420-0006', email: 'altitude@ruderalis.com'}},
        owner: {fullName: 'Dr. Elena Vasquez'},
        rating: {average: 4.9, count: 312, details: {five: 72, four: 16, three: 8, two: 3, one: 1}},
        price: {amount: 70, currency: 'GHS'},
        description: 'Gorilla Glue #4 is an award-winning hybrid that delivers heavy-handed euphoria and relaxation. Pungent earthy and sour aromas. With THC levels reaching 28%, this strain is recommended for experienced patients seeking powerful relief.\n\nTerpene Profile: Caryophyllene (dominant), Myrcene, Limonene\nEffects: Relaxed, Euphoric, Happy, Uplifted\nFlavors: Earthy, Pungent, Pine, Diesel\nMay help with: Pain, Stress, Insomnia, Depression, Muscle spasms',
        strain: 'Hybrid', status: 'active', category: 'Flower',
        image: featured, name: 'Gorilla Glue #4',
        thc: '28', cbd: '0.1', featured: true, sale: true,
        reviews,
        createdAt: '2025-10-15T10:00:00Z',
    },
];
